rtx.dlfg.enable = False
rtx.neuralRadianceCache.trainingMaxPathBounces = 6
rtx.neuralRadianceCache.qualityPreset = 0
rtx.graphicsPreset = 3
rtx.di.enableRayTracedBiasCorrection = False
rtx.restirGI.biasCorrectionMode = 1
rtx.dlssPreset = 0
rtx.neuralRadianceCache.targetNumTrainingIterations = 2
rtx.neuralRadianceCache.smallestResolvableFeatureSizeMeters = 0.06
rtx.russianRouletteMaxContinueProbability = 0.7
rtx.enableUnorderedResolveInIndirectRays = False
rtx.russianRoulette1stBounceMinContinueProbability = 0.4
rtx.enableTransmissionApproximationInIndirectRays = True
rtx.pathMaxBounces = 2
rtx.volumetrics.froxelDepthSlices = 48
rtx.neuralRadianceCache.terminationHeuristicThreshold = 0.001
rtx.denoiseDirectAndIndirectLightingSeparately = False
rtx.volumetrics.froxelGridResolutionScale = 16
rtx.neeCache.enable = False
rtx.rayreconstruction.model = 0
rtx.restirGI.useReflectionReprojection = False
rtx.reflexMode = 0
rtx.postfx.enable = False
rtx.upscalerType = 0
rtx.pathMinBounces = 0
rtx.enableStochasticAlphaBlend = False
rtx.volumetrics.enable = False
