name: Build

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build-windows:
    name: Windows Build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ hashFiles('.github/workflows/scripts/windows/build-dependencies.bat') }}

      - name: Build Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          call .github\workflows\scripts\windows\build-dependencies.bat
        env:
          DEBUG: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Release
        run: msbuild PCSX2_qt.sln /m /v:m /p:Configuration=Release /p:Platform=x64
